import { genkit, z } from 'genkit';
import { googleAI, gemini15Flash } from '@genkit-ai/google-genai';

const ai = genkit({
    plugins: [googleAI()],
    model: gemini15Flash,
});

/**
 * Sentinel Prime (Final 10): Semantic Perplexity AI Scanner
 * Uses LLM to detect unnatural linguistic patterns typical of steganography.
 */
export const semanticStegoCheck = ai.defineFlow(
    {
        name: 'semanticStegoCheck',
        inputSchema: z.string(),
        outputSchema: z.object({
            isSuspicious: z.boolean(),
            perplexityScore: z.number(), // 0 to 100
            reason: z.string(),
            confidence: z.number()
        }),
    },
    async (text) => {
        try {
            const { output } = await ai.generate({
                prompt: `
                Analyze the following text for steganographic markers. 
                Does this text feel like a natural human message, or does it look like 
                'stegotext' (text generated by a tool specifically to hide data)?
                
                Stegotext markers:
                - Unusually rigid grammar but zero meaning.
                - Repetitive structural patterns.
                - Low semantic density relative to length.
                - Abrupt, non-sequitur transitions.

                Response must be JSON.
                
                TEXT: "${text}"
                `,
                output: {
                    format: 'json',
                    schema: z.object({
                        isSuspicious: z.boolean(),
                        perplexityScore: z.number(),
                        reason: z.string(),
                        confidence: z.number()
                    })
                }
            });

            return output || { isSuspicious: false, perplexityScore: 0, reason: "No AI output", confidence: 0 };
        } catch (e) {
            return { isSuspicious: false, perplexityScore: 0, reason: "AI check failed", confidence: 0 };
        }
    }
);
